config/routes.rb
Rails.application.routes.draw do
#  resources :users
  devise_for :users
  resources :images do
    resources :tags
  end
  resources :users
  root to: "images#index"
  get 'tag/:id' => 'tags#index', :as => :tag
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :user
  has_and_belongs_to_many :tags

  validates :title, :url, :presence => true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :images

  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :images
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  #  binding.pry
  end

  def new
    @image = Image.new
  end

  def create
    @user = current_user
    @image = @user.images.create(title: params[:title], url: params[:url], user_id: @user.id)
    tag_array = params[:tags].split(',')
    tag_array.each do |tag|
      clean_tag = tag.strip
      @image.tags.create(name: clean_tag)
    end
    if @image.save
      flash[:notice] = "Image successfully added!"
      redirect_to images_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])

  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:notice] = "Image successfully updated!"
      redirect_to images_path
    else
      flash[:alert] = "Image did not update!"
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    flash[:notice] = "Image successfully deleted"
    redirect_to images_path
  end

  def show
    @image = Image.find(params[:id])
  end

  private
  def image_params
    params.require(:image).permit(:title, :url)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @profile = Profile.find(params[:id])
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    # binding.pry
    @tag = Tag.find(params[:id])
  end

  def new
    @users = User.all
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new
  end

  def create
    @image = Image.find(params[:image_id])
    @tag = @image.tags.new
    if tag_params[:name] != ""
      new_tag = Tag.find_or_create_by(tag_params)
      if @image.tags.include?(new_tag)
        flash[:notice] = "Image already has that tag"
        redirect_to new_image_tag_path(@image, @tag)
      else
        @image.tags.push(new_tag)
        flash[:notice] = "Tag successfully added!"
        redirect_to images_path
      end
    else
      flash[:alert] = "Tag name cannot be blank"
      redirect_to new_image_tag_path(@image, @tag)
    end

  end

  def edit
    @image = Image.find(params[:image_id])
    @tag = Tag.find(params[:id])
  end

  def update
    @image = Image.find(params[:image_id])
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
      flash[:notice] = "Tag successfully updated!"
      redirect_to image_path(@image)
    else
      flash[:alert] = "Tag did not update!"
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:image_id])
    @tag = Tag.find(params[:id])
    @tag.destroy
    flash[:notice] = "Tag successfully deleted"
    redirect_to image_path(@image)
  end

  private
  def tag_params
    params.require(:tag).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @tagged_photos = []
    Image.all.each do |image|
      image.tags.each do |tag|
        if tag.name == @user.email
          @tagged_photos.push(image)
        end
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/_form.html.erb
<%= render "layouts/errors", :object => @image %>
<h5>Please separate tags with a comma</h5>
  <%= form_tag @image do %>
    <%= label_tag :title %>
    <%= text_field_tag :title %>
    <%= label_tag :url %>
    <%= text_field_tag :url %>
    <%= label_tag :tags %>
    <%= text_field_tag :tags %>
    <%= submit_tag 'Create Image', class:"btn btn-lg btn-primary bigButton"%>
  <% end %>

app/views/images/edit.html.erb
<h1>Edit:</h1>

<%= render "layouts/errors", :object => @image %>

<%= form_for @image do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/images/index.html.erb
<h2>Recently posted images:</h2>

<% @images.each do |image| %>
  <div class="well">
    <h3><%= image.title %></h3>
    <h5>posted by <%= link_to image.user.email, user_path(image.user) %></h5>
    <img src="<%=image.url%>">
    <% if current_user && current_user.id == image.user.id %>
      <div id="outerLeft">
        <div class="inner">
          <%= button_to "edit", edit_image_path(image), class: 'btn btn-small btn-warning', method: "get" %>
        </div>
        <div class="inner">
          <%= button_to "delete", image_path(image), class: 'btn btn-small btn-danger', method: "delete",  :data =>
                              {:confirm => "Are you sure?",
                                method: "delete"
                                }%>
        </div>
      </div>
    <% end %>
    <% if image.tags.any? %>
      <h4>Tags:</h4>
      <% number_of_tags = image.tags.length %>
      <% image.tags.each_with_index do |tag, index| %>
        <% if index == number_of_tags - 1 %>
          <h5 class="makeInline"><%= link_to tag.name, tag_path(tag)%></h5>
        <% else %>
          <h5 class="makeInline"><%= link_to tag.name, tag_path(tag)%>,</h5>
        <% end %>
      <% end %>
    <% end %>
    <%= button_to "edit tags", image_path(image), class: 'btn btn-info', method: "get" %>
  </div>
<% end %>

<hr>
<% if current_user %>
  <div class="bigButton">
    <%= button_to "Add an image", new_image_path, class: 'btn btn-lg btn-primary', method: 'get' %>
  </div>
<% end %>

app/views/images/new.html.erb
<h1>Add an image:</h1>

<%= render 'form' %>

app/views/images/show.html.erb
<h1><%=@image.title%></h1>

<img src="<%=@image.url%>"%>

<h2>Tags:</h2>

<ul class="list-group">
  <% @image.tags.each do |tag| %>
    <li class="list-group-item">
      <%= link_to tag.name, tag_path(tag)%>
      <div id="outer">
        <div class="inner">
          <%= button_to "Edit Tag", edit_image_tag_path(@image, tag), method: "get", class: 'btn btn-sm btn-warning' %>
        </div>
        <div class="inner">
          <%= button_to "Delete Tag", image_tag_path(@image, tag), method: "delete", class: 'btn btn-sm btn-danger', :data => {:confirm => "Are you sure?", method: "delete" }%>
        </div>
      </div>
    </li>
  <% end %>
</ul>
<%= button_to "Add a Tag", new_image_tag_path(@image), class: "btn btn-lg btn-primary bigButton", method: "get" %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PictureTown</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "login", new_user_session_path %>
        <% end %>
      </div>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <div class="jumbotron">
        <div class="container-fluid">
          <h1>PictureTown</h1>
          <p>Social sharing and tagging of images!</p>
        </div>
        <nav class="navbar">
          <div class="navbar-class">
            <ul class="nav navbar-nav">
              <li class="active"><%= link_to 'Home', images_path %></li>
            </ul>
          </div>
        </nav>
      </div>
      <%= yield %>
      </div>
    </div>
  </body>
</html>

app/views/profiles/show.html.erb
<h1><%=@profile.username%></h1>

app/views/tags/edit.html.erb
<%= form_for [@image, @tag] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/tags/index.html.erb
<h1>Pictures with "<%= @tag.name %>" tag:</h1>

<% @tag.images.each do |image| %>
  <div class="well">
    <h3><%= image.title %><h3>
    <h5>posted by: <%=link_to image.user.email, user_path(image.user)%></h5>
    <img src="<%=image.url%>">
  </div>
  <hr>
<% end %>

app/views/tags/new.html.erb
<%= render "layouts/errors", :object => @tag %>

<h1>Add a tag to <%= @image.title %></h1>


<h3>Write a tag:</h3>
<%= form_for [@image, @tag] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

<hr>

<h3>Tag a user:</h3>
<%= form_for [@image, @tag] do |f| %>
  <%= f.select :name, options = options_from_collection_for_select(@users, 'email', 'email')%>
  <%= f.submit %>
<% end %>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <h5><%= user.username %> </h5>
<% end %>

app/views/users/show.html.erb
<h1><%=@user.email%>'s Profile</h1>

<hr>

<% if @tagged_photos.any? %>
  <div class="well">
    <h3>Tagged photos of <%=@user.email%>:</h3>

    <% @tagged_photos.each do |photo| %>
      <img src="<%=photo.url%>">
    <% end %>
  </div>
<% end %>